all:
	javac -Xlint:all sc.java

tar:
	tar -cvf cs328-assignment-4-tlerea1.tar --exclude='*.class' --exclude='*.tar.gz' --exclude='*.s' --exclude='*.dot' *
	gzip cs328-assignment-4-tlerea1.tar

clean:
	rm *.class
